@extends('layouts.app')
@php($editing = isset($asset))
@section('title', ($editing ? 'Edit' : 'Daftarkan').' Aset | Grapadi')
@section('content')
<section class="pt-28 pb-20 px-6"><div class="mx-auto max-w-4xl">
    <a href="{{ route('matching.dashboard') }}" class="text-sm text-primary">← Kembali ke dashboard</a><h1 class="mt-4 font-display text-4xl font-semibold text-white">{{ $editing ? 'Edit Aset' : 'Daftarkan Aset' }}</h1><p class="mt-2 text-gray-400">Lengkapi data dasar. Valuasi, appraisal, dan studi kelayakan tidak dilakukan pada tahap ini.</p>
    <div class="mt-7">@include('asset-matching.partials.alerts')</div>
    @if($editing && $asset->status === \App\Enums\AssetStatus::Published)<div class="mb-6 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-amber-200">Perubahan akan menyembunyikan aset dari katalog dan mengirimkannya kembali untuk review.</div>@endif
    <form method="POST" enctype="multipart/form-data" action="{{ $editing ? route('matching.assets.update', $asset) : route('matching.assets.store') }}" class="space-y-7">@csrf @if($editing)@method('PUT')@endif
        <div class="rounded-2xl border border-border-dark bg-surface-dark p-6"><h2 class="font-display text-2xl font-semibold text-white">Informasi Aset</h2><div class="mt-5 grid gap-5 sm:grid-cols-2">
            <label class="block text-sm text-gray-300 sm:col-span-2">Nama aset<input name="name" value="{{ old('name', $asset->name ?? '') }}" required class="mt-2 w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-white"></label>
            <label class="block text-sm text-gray-300">Kategori<select name="asset_category_id" required class="mt-2 w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-white"><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('asset_category_id', $asset->asset_category_id ?? '')==$category->id)>{{ $category->name }}</option>@endforeach</select></label>
            <label class="block text-sm text-gray-300">Luas (m²)<input name="area_sqm" type="number" min="0.01" step="0.01" value="{{ old('area_sqm', $asset->area_sqm ?? '') }}" required class="mt-2 w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-white"></label>
            <label class="block text-sm text-gray-300">Provinsi<input name="province" value="{{ old('province', $asset->province ?? '') }}" required class="mt-2 w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-white"></label>
            <label class="block text-sm text-gray-300">Kota/Kabupaten<input name="city" value="{{ old('city', $asset->city ?? '') }}" required class="mt-2 w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-white"></label>
            <label class="block text-sm text-gray-300 sm:col-span-2">Alamat lengkap <span class="text-gray-500">(tidak ditampilkan publik)</span><textarea name="full_address" rows="3" required class="mt-2 w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-white">{{ old('full_address', $asset->full_address ?? '') }}</textarea></label>
        </div></div>
        <div class="rounded-2xl border border-border-dark bg-surface-dark p-6"><h2 class="font-display text-2xl font-semibold text-white">Legalitas Dasar</h2><div class="mt-5 grid gap-5 sm:grid-cols-2">
            <label class="block text-sm text-gray-300">Jenis sertifikat<input name="certificate_type" value="{{ old('certificate_type', $asset->certificate_type ?? '') }}" placeholder="Contoh: SHM, HGB" required class="mt-2 w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-white"></label>
            <label class="block text-sm text-gray-300">Nomor sertifikat <span class="text-gray-500">(privat)</span><input name="certificate_number" value="{{ old('certificate_number', $asset->certificate_number ?? '') }}" required class="mt-2 w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-white"></label>
            <label class="block text-sm text-gray-300 sm:col-span-2">Scan sertifikat (PDF/JPG/PNG, maks. 10 MB)@if($editing)<span class="text-gray-500"> — kosongkan jika tidak diganti</span>@endif<input name="certificate_file" type="file" accept=".pdf,.jpg,.jpeg,.png" {{ $editing ? '' : 'required' }} class="mt-2 block w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-gray-300">@if($editing)<a class="mt-2 inline-block text-xs text-primary" href="{{ route('matching.assets.certificate', $asset) }}">Unduh dokumen saat ini</a>@endif</label>
        </div></div>
        <div class="rounded-2xl border border-border-dark bg-surface-dark p-6"><h2 class="font-display text-2xl font-semibold text-white">Status dan Tujuan</h2><div class="mt-5 grid gap-5 sm:grid-cols-2">
            @foreach([['condition','Kondisi aset',$conditions,'condition_notes','Keterangan kondisi'],['ownership_status','Status kepemilikan',$ownerships,'ownership_notes','Keterangan kepemilikan'],['utilization_status','Status pemanfaatan',$utilizations,'utilization_notes','Keterangan pemanfaatan']] as [$field,$label,$options,$notes,$notesLabel])
            <label class="block text-sm text-gray-300">{{ $label }}<select name="{{ $field }}" required class="mt-2 w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-white"><option value="">Pilih</option>@foreach($options as $value=>$text)<option value="{{ $value }}" @selected(old($field, isset($asset) ? $asset->{$field}->value : '')===$value)>{{ $text }}</option>@endforeach</select></label>
            <label class="block text-sm text-gray-300">{{ $notesLabel }} <span class="text-gray-500">(opsional)</span><textarea name="{{ $notes }}" rows="2" class="mt-2 w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-white">{{ old($notes, $asset->{$notes} ?? '') }}</textarea></label>@endforeach
            <label class="block text-sm text-gray-300 sm:col-span-2">Tujuan aset<select name="objective" required class="mt-2 w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-white"><option value="">Pilih satu tujuan</option>@foreach($objectives as $value=>$text)<option value="{{ $value }}" @selected(old('objective', isset($asset) ? $asset->objective->value : '')===$value)>{{ $text }}</option>@endforeach</select></label>
        </div></div>
        <div class="rounded-2xl border border-border-dark bg-surface-dark p-6"><h2 class="font-display text-2xl font-semibold text-white">Foto Aset</h2><p class="mt-1 text-sm text-gray-400">JPG, PNG, atau WebP; maksimal 5 MB per foto dan total 10 foto.</p>
            @if($editing && $asset->photos->isNotEmpty())<div class="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-4">@foreach($asset->photos as $photo)<label class="relative overflow-hidden rounded-xl border border-border-dark"><img src="{{ asset('storage/'.$photo->path) }}" class="h-32 w-full object-cover"><span class="flex items-center gap-2 bg-background-dark p-2 text-xs text-red-300"><input type="checkbox" name="delete_photo_ids[]" value="{{ $photo->id }}"> Hapus</span></label>@endforeach</div>@endif
            <input name="photos[]" type="file" accept="image/jpeg,image/png,image/webp" multiple {{ $editing ? '' : 'required' }} class="mt-5 block w-full rounded-xl border border-border-dark bg-background-dark px-4 py-3 text-gray-300">
        </div>
        <div class="flex justify-end gap-3"><a href="{{ route('matching.dashboard') }}" class="rounded-xl border border-border-dark px-6 py-3 text-gray-300">Batal</a><button class="rounded-xl bg-primary px-6 py-3 font-semibold text-background-dark">{{ $editing ? 'Simpan Perubahan' : 'Simpan Draft' }}</button></div>
    </form>
</div></section>
@endsection
