@extends('layouts.app')
@section('title', 'Dashboard Capital Connect | Grapadi')
@section('content')
<section class="pt-28 pb-20 px-6"><div class="mx-auto max-w-7xl">
    <div class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-sm uppercase tracking-widest text-primary">Dashboard</p><h1 class="mt-2 font-display text-4xl font-semibold text-white">Halo, {{ auth()->user()->name }}</h1></div><div class="flex gap-3"><a href="{{ route('matching.assets.create') }}" class="rounded-xl bg-primary px-5 py-3 font-semibold text-background-dark">+ Daftarkan Aset</a><form method="POST" action="{{ route('matching.logout') }}">@csrf<button class="rounded-xl border border-border-dark px-5 py-3 text-gray-300">Keluar</button></form></div></div>
    <div class="mt-8">@include('asset-matching.partials.alerts')</div>

    @if($notifications->isNotEmpty())<section class="mt-8"><h2 class="font-display text-2xl font-semibold text-white">Notifikasi</h2><div class="mt-4 space-y-3">@foreach($notifications as $notification)<a href="{{ $notification->data['url'] ?? '#' }}" class="block rounded-xl border {{ $notification->read_at ? 'border-border-dark' : 'border-primary/40' }} bg-surface-dark p-4"><p class="font-medium text-white">{{ $notification->data['title'] ?? 'Pembaruan aset' }}</p><p class="mt-1 text-sm text-gray-400">{{ $notification->data['message'] ?? '' }}</p></a>@endforeach</div></section>@endif

    <section class="mt-12"><div class="flex items-end justify-between"><div><h2 class="font-display text-3xl font-semibold text-white">Aset Saya</h2><p class="mt-1 text-gray-400">Kelola pengajuan dan pantau hasil review.</p></div></div>
        <div class="mt-5 overflow-x-auto rounded-2xl border border-border-dark"><table class="w-full min-w-[760px] bg-surface-dark text-left text-sm"><thead class="border-b border-border-dark text-gray-400"><tr><th class="p-4">Aset</th><th class="p-4">Kategori</th><th class="p-4">Listing/Tujuan</th><th class="p-4">Status Review</th><th class="p-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-border-dark">
        @forelse($assets as $asset)<tr><td class="p-4"><p class="font-semibold text-white">{{ $asset->name }}</p><p class="text-xs text-gray-500">{{ $asset->city }}, {{ $asset->province }}</p></td><td class="p-4 text-gray-300">{{ $asset->category->name }}</td><td class="p-4 text-gray-300"><span class="rounded-full bg-primary/10 px-3 py-1 text-xs text-primary">{{ $asset->listing_status->label() }}</span><p class="mt-2 text-xs text-gray-500">{{ $asset->objective->label() }}</p></td><td class="p-4"><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $asset->status === \App\Enums\AssetStatus::Published ? 'bg-emerald-500/10 text-emerald-300' : ($asset->status === \App\Enums\AssetStatus::RevisionRequired ? 'bg-red-500/10 text-red-300' : 'bg-primary/10 text-primary') }}">{{ $asset->status->label() }}</span>@if($asset->latest_review_notes)<p class="mt-2 max-w-sm text-xs text-gray-400">{{ $asset->latest_review_notes }}</p>@endif</td><td class="p-4"><div class="flex justify-end gap-2">
            @if(in_array($asset->status, [\App\Enums\AssetStatus::Draft, \App\Enums\AssetStatus::RevisionRequired, \App\Enums\AssetStatus::Published], true))<a href="{{ route('matching.assets.edit', $asset) }}" class="rounded-lg border border-border-dark px-3 py-2 text-primary">Edit</a>@endif
            @if(in_array($asset->status, [\App\Enums\AssetStatus::Draft, \App\Enums\AssetStatus::RevisionRequired], true))<form method="POST" action="{{ route('matching.assets.submit', $asset) }}">@csrf<button class="rounded-lg bg-primary px-3 py-2 font-semibold text-background-dark">Kirim Review</button></form>@endif
            @if($asset->status !== \App\Enums\AssetStatus::Archived)<form method="POST" action="{{ route('matching.assets.archive', $asset) }}" onsubmit="return confirm('Arsipkan aset ini?')">@csrf<button class="rounded-lg border border-red-500/30 px-3 py-2 text-red-300">Arsipkan</button></form>@endif
        </div></td></tr>@empty<tr><td colspan="5" class="p-10 text-center text-gray-400">Anda belum mendaftarkan aset.</td></tr>@endforelse
        </tbody></table></div>
    </section>

    <section class="mt-14"><h2 class="font-display text-3xl font-semibold text-white">Minat Saya</h2><p class="mt-1 text-gray-400">Minat resmi yang telah diteruskan kepada tim Grapadi.</p><div class="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
        @forelse($interests as $interest)<a href="{{ route('matching.show', $interest->asset) }}" class="rounded-2xl border border-border-dark bg-surface-dark p-5 hover:border-primary/50"><span class="text-xs text-primary">{{ $interest->asset->category->name }}</span><h3 class="mt-2 font-display text-2xl font-semibold text-white">{{ $interest->asset->name }}</h3><p class="mt-2 text-sm text-gray-400">{{ $interest->asset->city }}, {{ $interest->asset->province }}</p><div class="mt-4 flex items-center justify-between border-t border-border-dark pt-4"><span class="text-xs text-gray-500">Status tindak lanjut</span><span class="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{{ $interest->lead?->status_label ?? 'New Lead' }}</span></div></a>
        @empty<div class="rounded-2xl border border-border-dark bg-surface-dark p-8 text-gray-400 md:col-span-2 lg:col-span-3">Belum ada aset dalam daftar minat Anda. <a href="{{ route('matching.index') }}" class="text-primary">Jelajahi katalog</a>.</div>@endforelse
    </div></section>
</div></section>
@endsection
